var myName = "Madhulika";
var fullName = 'ayare';
var age = 22;
var weight = 60.2;
var isMarried = false;
var isLazy = true;
var typeOfMyName = typeof myName;
console.log("type of myName is", typeOfMyName);
console.log("type of fullname", typeof fullName);
console.log(typeof age, isMarried);